### ISSUE TITLE
Azul Zulu 1.8 JAXB implementation

### ISSUE THREAD

**Issue by Mieges** [plutext/docx4j-ImportXHTML#108]
Hello everyone, I have the following problem: When I clone the repository and do a checkout on 8_3_10 and execute a sample file “XhtmlToDocxAndBack.java” or “ConvertInXHTMLFile.java” (with correct paths), I get the following error message:

Exception in thread "main" java.lang.RuntimeException: javax.xml.bind.JAXBException: Can't create internal NamespacePrefixMapper
 - with linked exception:
[java.lang.ClassNotFoundException: org.docx4j.jaxb.suninternal.NamespacePrefixMapper]
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:941)
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:857)
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:797)
	at org.docx4j.model.styles.StyleTree.createVirtualStylesForDocDefaults(StyleTree.java:527)
	at org.docx4j.model.styles.StyleTree.init(StyleTree.java:141)
	at org.docx4j.model.styles.StyleTree.<init>(StyleTree.java:81)
	at org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart.getStyleTree(MainDocumentPart.java:203)
	at org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart.getStyleTree(MainDocumentPart.java:173)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.stylesToCSS(XHTMLImporterImpl.java:475)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.getRenderer(XHTMLImporterImpl.java:282)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:711)
	at org.docx4j.samples.ConvertInXHTMLFile.main(ConvertInXHTMLFile.java:107)
Caused by: javax.xml.bind.JAXBException: Can't create internal NamespacePrefixMapper
 - with linked exception:
[java.lang.ClassNotFoundException: org.docx4j.jaxb.suninternal.NamespacePrefixMapper]
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.getPrefixMapper(NamespacePrefixMapperUtils.java:67)
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:889)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.docx4j.jaxb.suninternal.NamespacePrefixMapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.getPrefixMapper(NamespacePrefixMapperUtils.java:63)
	... 12 more

I also get this message in a few more places.

I have tried both JAXB-Internal and JAXB RI. The errors remain the same. 

Also did mvn clean install.

The tests don't work for me either because of pddocument.

My goal is to get simple HTML (with inline CSS) correctly formatted in a Word document. 

I use:
IntelliJ
Maven 3
Java: Azul Zulu 1.8.0_432

I am relatively new here, please have some mercy :) 

Translated with DeepL.com (free version)

**Comment by plutext** [comment]
Hi Markus

I suspect the problem is that Azul Zulu 1.8.0_432 probably does not contain the old "Sun internal" JAXB implementation.

I would expect things to work if you include https://central.sonatype.com/artifact/org.docx4j/docx4j-JAXB-ReferenceImpl/8.3.13 or https://central.sonatype.com/artifact/org.docx4j/docx4j-JAXB-MOXy/8.3.13

So please try that again, and include any stack trace if it fails.

**Comment by Mieges** [comment]
Hello plutext, thank you very much for your reply! I hope you've had a good start to the new year. 
I have now tried both JAXB-MOXy and the JAXB-ReferenceImplementation in version 8.3.13 in branch 8_3_10. I get the same error both times with the same stack trace. 
I skipped the step with gpg 1.5 because there were errors with mvn clean install. I'll send the complete console output once, maybe it will help more. 
```
12:07:42.350 [main] INFO org.docx4j.jaxb.Context - java.vendor=Azul Systems, Inc.
12:07:42.352 [main] INFO org.docx4j.jaxb.Context - java.version=1.8.0_432
12:07:42.353 [main] INFO org.docx4j.jaxb.Context - java.vm.name=OpenJDK 64-Bit Server VM
12:07:45.418 [main] DEBUG org.docx4j.jaxb.Context - JAXB Context: com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl
12:07:45.418 [main] INFO org.docx4j.jaxb.Context - Using Java 6+ JAXB implementation
12:07:45.522 [main] DEBUG org.docx4j.jaxb.Context - .. other contexts loaded ..
12:07:45.533 [main] DEBUG org.docx4j.utils.ResourceUtils - Attempting to load: docx4j-ImportXHTML.properties
12:07:45.533 [main] DEBUG org.docx4j.utils.ResourceUtils - Trying Thread.currentThread().getContextClassLoader()
12:07:45.533 [main] WARN org.docx4j.utils.ResourceUtils - Couldn't get resource: docx4j-ImportXHTML.properties
12:07:45.533 [main] WARN org.docx4j.convert.in.xhtml.ImportXHTMLProperties - Couldn't find/read docx4j-ImportXHTML.properties; docx4j-ImportXHTML.properties not found via classloader.
12:07:45.549 [main] DEBUG org.docx4j.utils.ResourceUtils - Attempting to load: docx4j.properties
12:07:45.549 [main] DEBUG org.docx4j.utils.ResourceUtils - Trying Thread.currentThread().getContextClassLoader()
12:07:45.549 [main] WARN org.docx4j.utils.ResourceUtils - Couldn't get resource: docx4j.properties
12:07:45.549 [main] WARN org.docx4j.Docx4jProperties - Couldn't find/read docx4j.properties; docx4j.properties not found via classloader.
12:07:45.550 [main] DEBUG org.docx4j.utils.ResourceUtils - docx4j.fonts.microsoft.MicrosoftFonts resolved to org/docx4j/fonts/microsoft/MicrosoftFonts.xml
12:07:45.550 [main] DEBUG org.docx4j.utils.ResourceUtils - Attempting to load: org/docx4j/fonts/microsoft/MicrosoftFonts.xml
12:07:45.625 [main] INFO org.docx4j.openpackaging.packages.WordprocessingMLPackage - Using paper size: A4
12:07:45.626 [main] INFO org.docx4j.openpackaging.packages.WordprocessingMLPackage - Landscape orientation: false
12:07:45.641 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml on part /


12:07:45.646 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml on part /word/document.xml


12:07:45.647 [main] DEBUG org.docx4j.model.structure.PageDimensions - Using paper size: A4
12:07:45.647 [main] DEBUG org.docx4j.model.structure.PageDimensions - Landscape orientation: false
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-package.relationships+xml on part /_rels/.rels


12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.relationships.RelationshipsPart
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Constructed rp for /
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.relationships.RelationshipsPart
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.contenttype.ContentTypeManager - Registered rels
12:07:45.650 [main] INFO org.docx4j.openpackaging.parts.relationships.RelationshipsPart - adding part with proposed name: /word/document.xml
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Relativising target /word/document.xml against source /
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Result word/document.xml
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - rel exists: false
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Loading part /word/document.xml
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Parts - put part /word/document.xml
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart
12:07:45.650 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.651 [main] DEBUG org.docx4j.openpackaging.packages.WordprocessingMLPackage - Set shortcut for mainDoc
12:07:45.651 [main] DEBUG org.docx4j.openpackaging.Base - shortcut was set
12:07:45.651 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml on part /word/styles.xml


12:07:45.651 [main] DEBUG org.docx4j.utils.ResourceUtils - docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart.DefaultStyles resolved to org/docx4j/openpackaging/parts/WordprocessingML/styles.xml
12:07:45.651 [main] DEBUG org.docx4j.utils.ResourceUtils - Attempting to load: org/docx4j/openpackaging/parts/WordprocessingML/styles.xml
12:07:45.651 [main] DEBUG org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware - For org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart, unmarshall (no binder)
12:07:45.651 [main] DEBUG org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware - Unmarshalling /word/styles.xml
12:07:45.652 [main] DEBUG org.docx4j.jaxb.Docx4jUnmarshallerListener - org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart
12:07:45.692 [main] DEBUG org.docx4j.XmlUtils - Azul Systems, Inc.
12:07:45.692 [main] DEBUG org.docx4j.XmlUtils - 1.8.0_432
12:07:45.692 [main] INFO org.docx4j.XmlUtils - default SAXParserFactory property : null
 Please consider using Xerces.
12:07:45.693 [main] WARN org.docx4j.XmlUtils - actual SAXParserFactory: org.apache.xerces.jaxp.SAXParserFactoryImpl
12:07:45.693 [main] INFO org.docx4j.XmlUtils - default DocumentBuilderFactory property: null
 Please consider using Xerces.
12:07:45.694 [main] WARN org.docx4j.XmlUtils - actual DocumentBuilderFactory: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-package.relationships+xml on part /word/_rels/document.xml.rels


12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.relationships.RelationshipsPart
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Constructed rp for /word/document.xml
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.relationships.RelationshipsPart
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.contenttype.ContentTypeManager - Registered rels
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] INFO org.docx4j.openpackaging.parts.relationships.RelationshipsPart - adding part with proposed name: /word/styles.xml
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Relativising target /word/styles.xml against source /word/document.xml
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Result styles.xml
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - rel exists: false
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Loading part /word/styles.xml
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.698 [main] DEBUG org.docx4j.openpackaging.parts.Parts - put part /word/styles.xml
12:07:45.699 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.699 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart
12:07:45.699 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.699 [main] DEBUG org.docx4j.openpackaging.Base - shortcut was set
12:07:45.700 [main] INFO org.docx4j.utils.XPathFactoryUtil - xpath implementation: org.docx4j.org.apache.xpath.jaxp.XPathFactoryImpl
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-package.core-properties+xml on part /docProps/core.xml


12:07:45.702 [main] INFO org.docx4j.openpackaging.parts.relationships.RelationshipsPart - adding part with proposed name: /docProps/core.xml
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Relativising target /docProps/core.xml against source /
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Result docProps/core.xml
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - rel exists: false
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Loading part /docProps/core.xml
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Parts - put part /docProps/core.xml
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.DocPropsCorePart
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.packages.WordprocessingMLPackage - Set shortcut for docPropsCorePart
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.Base - shortcut was set
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-officedocument.extended-properties+xml on part /docProps/app.xml


12:07:45.702 [main] INFO org.docx4j.openpackaging.parts.relationships.RelationshipsPart - adding part with proposed name: /docProps/app.xml
12:07:45.702 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Relativising target /docProps/app.xml against source /
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Result docProps/app.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - rel exists: false
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Loading part /docProps/app.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Parts - put part /docProps/app.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.DocPropsExtendedPart
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.packages.WordprocessingMLPackage - Set shortcut for docPropsExtendedPart
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.Base - shortcut was set
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml on part /word/settings.xml


12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] INFO org.docx4j.openpackaging.parts.relationships.RelationshipsPart - adding part with proposed name: /word/settings.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Relativising target /word/settings.xml against source /word/document.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Result settings.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - rel exists: false
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Loading part /word/settings.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Parts - put part /word/settings.xml
12:07:45.703 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.WordprocessingML.DocumentSettingsPart
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.Base - shortcut was set
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.WordprocessingML.DocumentSettingsPart - No w:settings/w:compat element; creating..
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.Base - 
Set contentType application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml on part /word/numbering.xml


12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] INFO org.docx4j.openpackaging.parts.relationships.RelationshipsPart - adding part with proposed name: /word/numbering.xml
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Relativising target /word/numbering.xml against source /word/document.xml
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Result numbering.xml
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - rel exists: false
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.relationships.RelationshipsPart - Loading part /word/numbering.xml
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.704 [main] DEBUG org.docx4j.openpackaging.parts.Parts - put part /word/numbering.xml
12:07:45.705 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.705 [main] DEBUG org.docx4j.openpackaging.parts.Part - setPackage to null called for org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart
12:07:45.705 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.705 [main] DEBUG org.docx4j.openpackaging.Base - shortcut was set
12:07:45.705 [main] DEBUG org.docx4j.utils.ResourceUtils - docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.DefaultNumbering resolved to org/docx4j/openpackaging/parts/WordprocessingML/numbering.xml
12:07:45.705 [main] DEBUG org.docx4j.utils.ResourceUtils - Attempting to load: org/docx4j/openpackaging/parts/WordprocessingML/numbering.xml
12:07:45.705 [main] DEBUG org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware - For org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart, unmarshall (no binder)
12:07:45.705 [main] DEBUG org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware - Unmarshalling /word/numbering.xml
12:07:45.705 [main] DEBUG org.docx4j.jaxb.Docx4jUnmarshallerListener - org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart
12:07:45.712 [main] INFO org.docx4j.convert.in.xhtml.XHTMLImporterImpl - tableFormatting: CLASS_PLUS_OTHER
12:07:45.712 [main] INFO org.docx4j.convert.in.xhtml.XHTMLImporterImpl - paragraphFormatting: CLASS_PLUS_OTHER
12:07:45.712 [main] INFO org.docx4j.convert.in.xhtml.XHTMLImporterImpl - runFormatting: CLASS_PLUS_OTHER
12:07:45.718 [main] DEBUG org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart - Preparing StyleTree
12:07:45.719 [main] DEBUG org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart - Style with name Default Paragraph Font, id 'DefaultParagraphFont' is default character style
12:07:45.719 [main] DEBUG org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart - Style with name Normal, id 'Normal' is default paragraph style
12:07:45.719 [main] DEBUG org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart - Style with name Normal Table, id 'TableNormal' is default table style
12:07:45.720 [main] DEBUG org.docx4j.TraversalUtil - getting children of org.docx4j.wml.ArrayListWml
12:07:45.720 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.720 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.720 [main] DEBUG org.docx4j.openpackaging.parts.Part - package name: null
12:07:45.721 [main] DEBUG org.docx4j.model.styles.StyleTree - Set virtual style, id 'DocDefaults', name 'DocDefaults'
12:07:45.724 [main] DEBUG org.docx4j.jaxb.NamespacePrefixMapperUtils - testContext: com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl
12:07:45.724 [main] INFO org.docx4j.jaxb.NamespacePrefixMapperUtils - Using com.sun.xml.internal NamespacePrefixMapper
Exception in thread "main" java.lang.RuntimeException: javax.xml.bind.JAXBException: Can't create internal NamespacePrefixMapper
 - with linked exception:
[java.lang.ClassNotFoundException: org.docx4j.jaxb.suninternal.NamespacePrefixMapper]
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:941)
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:857)
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:797)
	at org.docx4j.model.styles.StyleTree.createVirtualStylesForDocDefaults(StyleTree.java:527)
	at org.docx4j.model.styles.StyleTree.init(StyleTree.java:141)
	at org.docx4j.model.styles.StyleTree.<init>(StyleTree.java:81)
	at org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart.getStyleTree(MainDocumentPart.java:203)
	at org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart.getStyleTree(MainDocumentPart.java:173)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.stylesToCSS(XHTMLImporterImpl.java:475)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.getRenderer(XHTMLImporterImpl.java:282)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:711)
	at org.docx4j.samples.ConvertInXHTMLFile.main(ConvertInXHTMLFile.java:107)
Caused by: javax.xml.bind.JAXBException: Can't create internal NamespacePrefixMapper
 - with linked exception:
[java.lang.ClassNotFoundException: org.docx4j.jaxb.suninternal.NamespacePrefixMapper]
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.getPrefixMapper(NamespacePrefixMapperUtils.java:67)
	at org.docx4j.XmlUtils.marshaltoString(XmlUtils.java:889)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.docx4j.jaxb.suninternal.NamespacePrefixMapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.getPrefixMapper(NamespacePrefixMapperUtils.java:63)
	... 12 more

Process finished with exit code 1
```

**Comment by Mieges** [comment]
Okay it just worked somehow with RI 8.3.13. 
I changed 
```
		<dependency>
		  <groupId>org.docx4j</groupId>
		  <artifactId>docx4j-core</artifactId>
			<version>8.3.10</version>
		</dependency>
```
to 

```
		<dependency>
		  <groupId>org.docx4j</groupId>
		  <artifactId>docx4j-core</artifactId>
			<version>8.3.13</version>
		</dependency>
```
and it worked. When I switched back it also suddenly worked. Thank you for your help and I wish you the best! :)
