### ISSUE TITLE
Failed to import a link with '&lt;' '&gt;'

### ISSUE THREAD

**Issue by wuzhengmao** [plutext/docx4j-ImportXHTML#20]
This is a simple link
&lt;a href="javascript:void(0);"&gt;&amp;lt;&amp;gt;&lt;/a&gt;

It will failed to import when we surround it with &lt;p&gt; as following
&lt;p&gt;&lt;a href="javascript:void(0);"&gt;&amp;lt;&amp;gt;&lt;/a&gt;&lt;/p&gt;

**Comment by plutext** [comment]
org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(Unknown Source)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at org.docx4j.XmlUtils.unmarshalString(XmlUtils.java:433)
	at org.docx4j.XmlUtils.unmarshalString(XmlUtils.java:413)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.createHyperlink(XHTMLImporterImpl.java:2160)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.processInlineBox(XHTMLImporterImpl.java:1691)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1233)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:797)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:681)
	at org.docx4j.samples.ConvertInXHTMLFragment.main(ConvertInXHTMLFragment.java:96)

The fix is simple, modify https://github.com/plutext/docx4j-ImportXHTML/blob/master/src/main/java/org/docx4j/convert/in/xhtml/XHTMLImporterImpl.java at line 2115 so '<' is replaced with &lt; [i hope github didn't mangle that!]

Happy to accept a pull request
