### ISSUE TITLE
nested tables causes TableHelper.java to crash

### ISSUE THREAD

**Issue by thelliez** [plutext/docx4j-ImportXHTML#29]
Here is the fragment of HTML that causes the crash.  It does not crash if the nested table does not contain 'align="left"'  (nested table).

```
<table cellpadding="3" cellspacing="1" style="page-break-before: always">
        <td class="padded" style="border-top: 1px solid #999999; border-bottom: none; border-left: none; border-right: none;"> 
            <table align="left"><tbody><tr><td >A</td></tr></tbody></table> 
        </td>
    </tr>
</table>
```

Here is the exception:

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.docx4j.convert.in.xhtml.TableHelper.setupTblGrid(TableHelper.java:219)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:982)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1260)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1240)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:814)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:495)

**Comment by plutext** [comment]
Where the table is nested and it sets align="left", tableBox.getColumnPos() returns the wrong value

https://github.com/flyingsaucerproject/flyingsaucer/blob/master/flying-saucer-core/src/main/java/org/xhtmlrenderer/newtable/TableBox.java has not changed since before June 2012 (but perhaps the issue is fixed somewhere else in that code base?)

**Comment by achimmihca** [comment]
In the given example, there is a `</tr>` without opening `<tr>`.
Not sure if this is the root of the issue or just a copy/paste error...

**Comment by plutext** [comment]
```
<html>
<body>
<table cellpadding="3" cellspacing="1" style="page-break-before: always">
    <tr>
        <td class="padded" style="border-top: 1px solid #999999; border-bottom: none; border-left: none; border-right: none;"> 
            <table align="left"><tbody><tr><td >A</td></tr></tbody></table> 
        </td>
    </tr>
</table>
</body>
</html>
```
seems to work ok in branch https://github.com/plutext/docx4j-ImportXHTML/tree/openhtmltopdf
