### ISSUE TITLE
OutOfMemoryError while converting html to docx

### ISSUE THREAD

**Issue by titanseason** [plutext/docx4j-ImportXHTML#55]
I'm using docx4j-ImportXHTML v6.1.0, to convert html to docx. But OutOfMemoryError happened.

Here is my sample code.
```
public void doConvert(File srcFile) {
        try {
            WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.createPackage();

            NumberingDefinitionsPart ndp = new NumberingDefinitionsPart();
            wordMLPackage.getMainDocumentPart().addTargetPart(ndp);
            ndp.unmarshalDefaultNumbering();

            XHTMLImporter xhtmlImporter = new XHTMLImporterImpl(wordMLPackage);
            xhtmlImporter.setHyperlinkStyle("Hyperlink");

            String htmlContent = getHtmlContent(srcFile);
           //  replace xml not supported characters. See more at: 
           // https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML
            String unescape = HtmlCharacterEntityConverter.unescape(htmlContent);
            String baseUrl = srcFile.getParentFile().toURI().toString();
            List<Object> objs = xhtmlImporter.convert(unescape, baseUrl);
            wordMLPackage.getMainDocumentPart().getContent().addAll(objs);
            // mdp.addAltChunk(AltChunkType.Xhtml, input);

            wordMLPackage.save(destFile);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private static String getHtmlContent(File file) {
        try {
            Document document = Jsoup.parse(file, null, file.getParent());
            document.outputSettings().prettyPrint(true).syntax(OutputSettings.Syntax.xml);

            return document.html();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }
```

You can find the demo html [here ](https://github.com/titanseason/java-samples/tree/master/docx4j/assets)

StackTrace: 
```
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at org.docx4j.org.xhtmlrenderer.util.ImageUtil.createCompatibleBufferedImage(ImageUtil.java:117)
	at org.docx4j.org.xhtmlrenderer.util.ImageUtil.convertToBufferedImage(ImageUtil.java:246)
	at org.docx4j.org.xhtmlrenderer.util.ImageUtil$AbstractFastScaler.getScaledInstance(ImageUtil.java:301)
	at org.docx4j.org.xhtmlrenderer.util.ImageUtil.getScaledInstance(ImageUtil.java:174)
	at org.docx4j.org.xhtmlrenderer.util.ImageUtil.getScaledInstance(ImageUtil.java:204)
	at org.docx4j.org.xhtmlrenderer.swing.AWTFSImage$NewAWTFSImage.scale(AWTFSImage.java:72)
	at org.docx4j.org.xhtmlrenderer.docx.Docx4jReplacedElementFactory.createReplacedElement(Docx4jReplacedElementFactory.java:60)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.calcDimensions(BlockBox.java:677)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.calcDimensions(BlockBox.java:631)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:778)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:735)
	at org.docx4j.org.xhtmlrenderer.layout.InlineBoxing.layoutInlineBlockContent(InlineBoxing.java:203)
	at org.docx4j.org.xhtmlrenderer.layout.InlineBoxing.layoutContent(InlineBoxing.java:165)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layoutInlineChildren(BlockBox.java:964)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:943)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:818)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:735)
	at org.docx4j.org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:61)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:947)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:818)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:735)
	at org.docx4j.org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:61)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:947)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:818)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:735)
	at org.docx4j.org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:61)
	at org.docx4j.org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:947)
```
I traced the stack, and at `ImageUtil.createCompatibleBufferedImage(ImageUtil.java:117)`, the image size is 12360x17560, But in fact the image is 618x878. You can search 'image001' in html content

**Comment by titanseason** [comment]
I think the code  `fsImage.scale(cssWidth, cssHeight) ` at 
 `Docx4jReplacedElementFactory#createReplacedElement(Line: 60)`, should be  `fsImage.scale(cssWidth / c.getDotsPerPixel(), cssHeight / c.getDotsPerPixel()) `

**Comment by jwhitmarsh** [comment]
@titanseason sorry to comment on a 2.5 year old issue, but did you ever resolve this?
