### ISSUE TITLE
java.lang.NoSuchMethodError: org.docx4j.org.apache.xml.serializer.SerializerFactory.getSerializer

### ISSUE THREAD

**Issue by bewithdhanu** [plutext/docx4j-ImportXHTML#61]
```
WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(file);
HTMLSettings htmlSettings = Docx4J.createHTMLSettings();
htmlSettings.setWmlPackage(wordMLPackage);
htmlSettings.setImageDirPath(dir + File.separator + file.getName() + "_files");
htmlSettings.setImageTargetUri(dir + File.separator + file.getName() + "_files");
//SdtWriter.registerTagHandler("HTML_ELEMENT", new SdtToListSdtTagHandler());
htmlSettings.getFeatures().remove(ConversionFeatures.PP_HTML_COLLECT_LISTS);
String htmlFilePath = dir + File.separator + file.getName() + ".html";
OutputStream os = new java.io.FileOutputStream(htmlFilePath);
Docx4J.toHTML(htmlSettings, os, Docx4J.FLAG_EXPORT_PREFER_XSL);
```

I am having this java.lang.NoSuchMethodError in this line
`Docx4J.toHTML(htmlSettings, os, Docx4J.FLAG_EXPORT_PREFER_XSL);`

Exception:

```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.docx4j.org.apache.xml.serializer.SerializerFactory.getSerializer(Ljava/util/Properties;)Lorg/docx4j/org/apache/xml/serializer/Serializer;
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:978)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.docx4j.org.apache.xml.serializer.SerializerFactory.getSerializer(Ljava/util/Properties;)Lorg/docx4j/org/apache/xml/serializer/Serializer;
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.createSerializationHandler(TransformerImpl.java:1174)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.createSerializationHandler(TransformerImpl.java:1063)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1270)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1253)
	at org.docx4j.XmlUtils.transform(XmlUtils.java:1360)
	at org.docx4j.XmlUtils.transform(XmlUtils.java:1191)
	at org.docx4j.convert.out.common.AbstractXsltExporterDelegate.process(AbstractXsltExporterDelegate.java:66)
	at org.docx4j.convert.out.html.HTMLExporterXslt$HTMLExporterXsltDelegate.process(HTMLExporterXslt.java:153)
	at org.docx4j.convert.out.html.HTMLExporterXslt$HTMLExporterXsltDelegate.process(HTMLExporterXslt.java:101)
	at org.docx4j.convert.out.common.AbstractWmlExporter.process(AbstractWmlExporter.java:63)
	at org.docx4j.convert.out.common.AbstractWmlExporter.process(AbstractWmlExporter.java:32)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:78)
	at org.docx4j.Docx4J.toHTML(Docx4J.java:830)
	at com.cepoch.wyzewaze.docUtils.Docx.docxToHtml(Docx.java:42)
	at com.cepoch.wyzewaze.controller.TemplateController.uploadTemplate(TemplateController.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	... 28 common frames omitted
```

**Comment by bewithdhanu** [comment]
While I am executing this in main method it works really fine
but after integrating this in a project I am having this issue
can someone help me in finding the solution?
