### ISSUE TITLE
WordprocessingML.StyleDefinitionsPart.getCss()' on a null object reference

### ISSUE THREAD

**Issue by gilshallem** [plutext/docx4j-ImportXHTML#70]
Hi
I'm trying to convert html to docx on android

My gradle:
`implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'javax.xml.stream:stax-api:1.0-2'
    implementation 'com.fasterxml:aalto-xml:1.2.2'
    implementation('org.docx4j:docx4j-ImportXHTML:8.0.0'){
       exclude module: 'commons-io'
    }`

Code: 
`WordprocessingMLPackage docxOut = WordprocessingMLPackage.createPackage();
            //NumberingDefinitionsPart ndp = new NumberingDefinitionsPart();
            //docxOut.getMainDocumentPart().addTargetPart(ndp);
            // ndp.unmarshalDefaultNumbering();

            XHTMLImporterImpl XHTMLImporter = new XHTMLImporterImpl(docxOut);
            //XHTMLImporter.setHyperlinkStyle("Hyperlink");
            htmlString = "<html><head><title></title></head><body>hi</body></html>";
            //docxOut.getMainDocumentPart().getStyleDefinitionsPart(true);

            docxOut.getMainDocumentPart().getContent().addAll(
                    XHTMLImporter.convert(htmlString, null) );

            OutputStream out = SafHelper3.createOutputStream(context, dir, fileName);
            docxOut.save(out);`

Error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.docx4j.openpackaging.parts.WordprocessingML.StyleDefinitionsPart.getCss()' on a null object reference
        at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.stylesToCSS(XHTMLImporterImpl.java:460)
        at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.getRenderer(XHTMLImporterImpl.java:271)
        at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:663)`

**Comment by plutext** [comment]
Can't reproduce in Java env with either ImportXHTML:8.0.0 or ImportXHTML:8.2.0
