### ISSUE TITLE
error :XhtmlToDocxAndBack.java 

### ISSUE THREAD

**Issue by edilyxin** [plutext/docx4j-ImportXHTML#76]
Hi borthor

I found an bug on line 78 of the XHTMLToDocxAndBack.java file.
The specific errors are as follows:

Exception in thread "main" java.lang.ClassCastException: java.math.BigInteger cannot be cast to org.docx4j.wml.CTSignedTwipsMeasure
	at org.docx4j.model.properties.run.Spacing.set(Spacing.java:115)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.addRunProperties(XHTMLImporterImpl.java:2520)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.formatRPr(XHTMLImporterImpl.java:2243)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.addRun(XHTMLImporterImpl.java:2200)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.addRuns(XHTMLImporterImpl.java:2174)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.processInlineBoxContent(XHTMLImporterImpl.java:2099)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.processInlineBox(XHTMLImporterImpl.java:2052)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverseBlockBox(XHTMLImporterImpl.java:1393)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:915)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverseBlockBox(XHTMLImporterImpl.java:1377)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:915)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverseBlockBox(XHTMLImporterImpl.java:1377)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:915)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverseBlockBox(XHTMLImporterImpl.java:1377)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:915)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:906)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:708)
	at org.docx4j.samples.XhtmlToDocxAndBack.main(XhtmlToDocxAndBack.java:78)

In this example, letter-spacing is not set. The default value is normal.So this error occurred, can you fix it? My program also reported this error when converting.

**Comment by plutext** [comment]
Thanks for this issue using docx4j 8.3.0; fixed at https://github.com/plutext/docx4j/commit/3d2cbe25370a46e133f8698d8e4cddacaa07d139
and will be in an 8.3.1 release next week.
