### ISSUE TITLE
Inline base64 images are not supported?

### ISSUE THREAD

**Issue by ghost** [plutext/docx4j-ImportXHTML#90]
Hi,

I'm using v8.0.0 for docx4j-ImportXHTML and I have in my html base64 inline images. I receive the following error.

Do I need to add something else?

```
java.lang.NoSuchMethodError: org.docx4j.openpackaging.parts.WordprocessingML.BinaryPartAbstractImage.createImageInline(Ljava/lang/String;Ljava/lang/String;IIZ)Lorg/docx4j/dml/wordprocessingDrawing/Inline;
	at org.docx4j.convert.in.xhtml.XHTMLImageHandlerDefault.addImage(XHTMLImageHandlerDefault.java:140)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.addImage(XHTMLImporterImpl.java:1702)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1238)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1304)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:1284)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.traverse(XHTMLImporterImpl.java:825)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:698)
```

**Comment by ghost** [comment]
I had 8.0.0 and it seems that in 8.3.8 it is supported...thanks
